-- 1. Create Resources Table
CREATE TABLE IF NOT EXISTS public.resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    author_id UUID REFERENCES public.profiles(id),
    wing_id TEXT,
    title TEXT,
    content TEXT,
    type TEXT, -- 'text', 'link', 'image'
    upvotes INTEGER DEFAULT 0,
    upvoted_by TEXT[] DEFAULT '{}'
);

-- 2. Update Comments Table to support Resources
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='comments' AND column_name='resource_id') THEN
        ALTER TABLE public.comments ADD COLUMN resource_id BIGINT REFERENCES public.resources(id) ON DELETE CASCADE;
    END IF;
END $$;

-- 3. Resource Upvote RPC
CREATE OR REPLACE FUNCTION public.handle_resource_upvote(target_res_id BIGINT, user_alias TEXT)
RETURNS json AS $$
DECLARE
    updated_res RECORD;
BEGIN
    UPDATE public.resources
    SET 
        upvotes = COALESCE(upvotes, 0) + 1,
        upvoted_by = array_append(COALESCE(upvoted_by, ARRAY[]::TEXT[]), user_alias)
    WHERE id = target_res_id
    RETURNING * INTO updated_res;

    UPDATE public.profiles
    SET xp = COALESCE(xp, 0) + 5
    WHERE id = updated_res.author_id;

    RETURN row_to_json(updated_res);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Relax permissions for resources
ALTER TABLE public.resources DISABLE ROW LEVEL SECURITY;
GRANT ALL ON public.resources TO authenticated;
GRANT ALL ON public.resources TO anon;
